name: catnap
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_cupertino_date_picker: ^1.0.26+2
  flutter_local_notifications: ^1.3.0
  intl: ^0.15.8
  time: ^1.3.0
  audioplayers: ^0.17.0
  animated_text_kit: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Comfortaa-Bold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-Regular.ttf
    - family: Blogger
      fonts:
        - asset: fonts/blogger-sans.regular.ttf
    - family: MadelynFill
      fonts:
        - asset: fonts/MadelynFill.otf